<?php
/**
 * Created by PhpStorm.
 * User: justinwang
 * Date: 27/8/18
 * Time: 3:20 PM
 */

namespace App\models\management;
use App\models\BaseModel;
use App\models\User;

class RegionTerritoryReport extends BaseModel
{
    const TABLE_NAME        = 'nissan_region_territory_reports';

    const DEPT_SALES = 'Sales';
    const DEPT_SERVICE = 'Service';
    const DEPT_PARTS = 'Parts';
    const DEPT_ADMINISTRATOR = 'Administration';
    const DEPT_VPC = 'VPC';

    // 4 regions
    const REGION_EASTERN             = 1;
    const REGION_NORTHERN            = 2;
    const REGION_SOUTHERN            = 3;
    const REGION_WESTERN_AND_CENTRAL = 4;
    const REGION_UNKNOWN             = 0;

    // Active values
    const ACTIVE        = 1;
    const INACTIVE      = 2;
    const INELIGIBLE    = 3;

    // Special case
    const PREFIX_OF_USELESS_DEALER_CODE = '5500'; // 任何55开始的 dealer code 都是可以忽略的
    const USELESS_DEALER_CODE           = '141';// 这个 dealer code 是测试用的

    protected $tableName    = 'nissan_region_territory_reports';

    public static $REGIONS = [
        'Southern Region'           =>self::REGION_SOUTHERN,
        'Western & Central Region'  =>self::REGION_WESTERN_AND_CENTRAL,
        'Eastern Region'            =>self::REGION_EASTERN,
        'Northern Region'           =>self::REGION_NORTHERN,
        'Eastern-NFSA Region'       =>self::REGION_EASTERN,
        'Western & Central-NFSA Region' =>self::REGION_WESTERN_AND_CENTRAL,
    ];

    public function __construct(User $user = null)
    {
        parent::__construct($user);
    }

    /**
     * Persistent record
     * @return \App\core\Model|bool
     */
    public function save()
    {
        // Only save when the employee_code field is not empty
        if(empty($this->employee_code)){
            return false;
        }else{
            $this->region_id = self::GetRegionCode($this->region_name);
            $this->period = env('YEAR');
            return parent::save(); // TODO: Change the autogenerated stub
        }
    }

    /**
     * Get Region Code
     * @param $name
     * @return int|mixed
     */
    public static function GetRegionCode($name){
        return isset(self::$REGIONS[$name]) ? self::$REGIONS[$name] : self::REGION_UNKNOWN;
    }

    /**
     * Get region code by Given name
     * @param $name
     * @return int|mixed
     */
    public static function GetRegionCodeWithShortName($name){
        if(is_array($name)){
            $name = $name[0];
        }
        $map = [
            'Southern'           =>self::REGION_SOUTHERN,
            'S'           =>self::REGION_SOUTHERN,
            'Western'            =>self::REGION_WESTERN_AND_CENTRAL,
            'W'            =>self::REGION_WESTERN_AND_CENTRAL,
            'Western & Central'  =>self::REGION_WESTERN_AND_CENTRAL,
            'Eastern'            =>self::REGION_EASTERN,
            'E'            =>self::REGION_EASTERN,
            'Northern'           =>self::REGION_NORTHERN,
            'N'           =>self::REGION_NORTHERN,
        ];
        return isset($map[$name]) ? $map[$name] : self::REGION_UNKNOWN;
    }

    /**
     * Search territory report by region codes. Only active records will be return
     * @param $codes
     * @return array|bool
     */
    public static function GetByRegionCodes($codes){
        $database = self::DB();
        if(count($codes) === 1){
            $codes = $codes[0];
        }

        return $database->select(self::TABLE_NAME,[
            'dealer_name(d)','registered(c)',
            'sp_code(s)','n_fullname(f)','employee_code(e)','position(p)','cr_ytd(y)',
            'credits_monthly_04(c04)','credits_monthly_05(c05)','credits_monthly_06(c06)','credits_monthly_07(c07)',
            'credits_monthly_08(c08)','credits_monthly_09(c09)','credits_monthly_10(c10)','credits_monthly_11(c11)',
            'credits_monthly_12(c12)','credits_monthly_01(c01)','credits_monthly_02(c02)','credits_monthly_03(c03)',
        ],[
            'AND'=>[
                'region_id'=>self::GetRegionCodeWithShortName($codes),
                'period'=>env('YEAR'),
                'active'=>self::ACTIVE
            ]
        ]);
    }

    /**
     * Search territory report by region codes
     * @param $codes
     * @return array|bool
     */
    public static function GetByEmployeeCodeRegionCodes($codes){
        $database = self::DB();
        if(count($codes) === 1){
            $codes = self::GetRegionCodeWithShortName($codes[0]);
        }
        return $database->select(self::TABLE_NAME,[
            'region_code','dealer_name','employee_code','n_fullname','sp_code','position','registered'
        ],[
            'AND'=>[
                'region_id'=>$codes,
                'period'=>env('YEAR')
            ]
        ]);
    }

    /**
     * Active by employee code
     * @param $code
     * @return array|bool
     */
    public static function ActiveIt($code){
        $database = self::DB();

        return $database->update(self::TABLE_NAME,
            ['active'=>self::ACTIVE],
            ['employee_code'=>$code]
        );
    }

    /**
     * Inactive by employee code
     * @param string $code
     * @param string $status
     * @return array|bool
     */
    public static function InactiveIt($code,$status){
        $database = self::DB();

        if(strtolower($status) === 'inactive'){
            $status = self::INACTIVE;
        }else{
            $status = self::INELIGIBLE;
        }

        return $database->update(self::TABLE_NAME,
            ['active'=>$status],
            ['employee_code'=>$code]
        );
    }

    /**
     * Make user's position string shorter as abbr. For better performance when sending to the client through internet
     * @param $pos
     * @return null|string
     */
    public static function ShortenPositionString($pos){
        $abbr = null;
        switch ($pos){
            case 'F & I Manager':
                $abbr = User::FI;
                break;
            case 'Parts Manager':
                $abbr = User::PARTS_MANAGER;
                break;
            case 'Parts Sales Representative':
                $abbr = User::PARTS_SALES_REP;
                break;
            case 'Sales Manager':
                $abbr = User::SALES_MANAGER;
                break;
            case 'Retail Sales Consultant':
                $abbr = User::RETAIL_SALES_CONSULTANTS;
                break;
            case 'Service Advisor':
                $abbr = User::SERVICE_ADVISERS;
                break;
            case 'Financial Controller':
                $abbr = User::FINANCE_CONTROLLER;
                break;
            case 'Stock Controller':
                $abbr = User::STOCK_CONTROLLER;
                break;
            case 'Service Manager':
                $abbr = User::SERVICE_MANAGER;
                break;
            case 'Fleet Sales Consultant':
                $abbr = User::FLEET_SALES_CONSULTANTS;
                break;
            case 'Fleet Sales Manager':
                $abbr = User::FLEET_SALES_MANAGER;
                break;
            default:
                break;
        }
        return $abbr;
    }
}