<?php
/**
 * Created by PhpStorm.
 * User: justinwang
 * Date: 27/8/18
 * Time: 3:20 PM
 */

namespace App\models\management;
use App\models\BaseModel;
use App\models\User;

class RegionTerritoryReport extends BaseModel
{
    const TABLE_NAME        = 'nissan_region_territory_reports';

    const DEPT_SALES = 'Sales';
    const DEPT_SERVICE = 'Service';
    const DEPT_PARTS = 'Parts';
    const DEPT_ADMINISTRATOR = 'Administration';
    const DEPT_VPC = 'VPC';

    // 4 regions
    const REGION_EASTERN             = 1;
    const REGION_NORTHERN            = 2;
    const REGION_SOUTHERN            = 3;
    const REGION_WESTERN_AND_CENTRAL = 4;
    const REGION_UNKNOWN             = 0;

    protected $tableName    = 'nissan_region_territory_reports';

    public function __construct(User $user = null)
    {
        parent::__construct($user);
    }

    /**
     * Persistent record
     * @return \App\core\Model|bool
     */
    public function save()
    {
        // Only save when the employee_code field is not empty
        if(empty($this->employee_code)){
            return false;
        }else{
            $this->region_id = self::GetRegionCode($this->region_name);
            $this->period = env('YEAR');
            return parent::save(); // TODO: Change the autogenerated stub
        }
    }

    public static function GetRegionCode($name){
        $map = [
            'Southern Region'           =>self::REGION_SOUTHERN,
            'Western & Central Region'  =>self::REGION_WESTERN_AND_CENTRAL,
            'Eastern Region'            =>self::REGION_EASTERN,
            'Northern Region'           =>self::REGION_NORTHERN,
        ];
        return isset($map[$name]) ? $map[$name] : self::REGION_UNKNOWN;
    }
}