<?php
/**
 * Created by PhpStorm.
 * User: justinwang
 * Date: 23/7/18
 * Time: 5:02 PM
 */

namespace App\controller;

use App\core\BaseController;
use App\models\nissan\Credit;
use App\models\nissan\DataSource;
use App\models\nissan\Events;
use App\models\nissan\History;
use App\models\nissan\Ranking;
use App\models\role\FI;
use App\models\role\IRole;
use App\models\role\RetailSalesConsultant;
use App\models\User;
use Carbon\Carbon;
use Klein\Request;
use Klein\Response;
use Zend\Json\Json;

class DashboardController extends BaseController
{
    protected $currentUserId = null;

    /**
     * @var User
     */
    protected $userObject = null;
    /**
     * If the current user has multiple roles at same time
     * @var bool
     */
    protected $userHasMultipleRoles = false;
    /**
     * 这个是一个要操作的数据表名称, 和用户当前提交上来的 asRole 相关
     * @var null |string
     */
    protected $targetTableName  = null;
    /**
     * 这个是本次请求作为的角色
     * @var null |string
     */
    protected $asRole           = null;

    /**
     * Data for metrics
     * @var null
     */
    protected $metricsData = null;
    protected $excellence = null;

    public function __construct(Request $request, Response $response)
    {
        parent::__construct($request, $response);
        $userData = session_get('user_data_array',true);
        if($userData && isset($userData['id'])){
            $this->currentUserId = $userData['id'];
            $this->userObject = new User($this->currentUserId);
        }else{
            // Session expired, go to login
            $response->redirect('/')->send();
            exit;
        }
    }

    /**
     * Before render hook
     * @param null $param
     */
    public function beforeRender($param = null)
    {
        parent::beforeRender($param); // TODO: Change the autogenerated stub

        if($this->userObject){
            $this->dataForView['user'] = $this->userObject;
            // 从原来的代码看, 似乎这两个也是必须的
            $this->dataForView['positions'] =
                DataSource::GetPositionList($this->userObject);

            $this->dataForView['multiple_role_metrics'] =
                DataSource::GetDataAllPositions($this->userObject);

            $this->dataForView['table_role_array'] =
                DataSource::GetTableRoleMetrics($this->userObject);
        }
    }


    /**
     * @param IRole $role
     * @param int $ytd
     */
    private function _prepareForFinanceAndInsurance(IRole $role,$ytd){
        $this->dataForView['dash'] = $role->getDashboardViewData($this->metricsData, $ytd);
        $this->dataForView['dash_template_file_name'] = $role->getTemplateName();
        $this->dataForView['extra_js'] = [
            'https://www.gstatic.com/charts/loader.js',
            asset('js/dashboard/'.$role->getTemplateName().'.js')
        ];
    }

    private function _prepareDashboardData(IRole $role, $ytd = null){
        $ytd = is_null($ytd) ? env('YEAR',2017) : $ytd;
        $this->dataForView['dashboard'] = $role->getDashboardViewData($this->dataForView,$ytd);
        $this->dataForView['calendar_events'] = Events::LoadForCalendarEvents();

//        echo Json::prettyPrint(Json::encode($this->dataForView['nissan_events']));
//        dd($this->dataForView['nissan_events']);

        $this->dataForView['metrics_template_file_name'] = $role->getTemplateName();

        $this->dataForView['extra_css'] = [
            asset('/includes/fullcalendar/fullcalendar.min.css')
        ];

        $this->dataForView['extra_js'] = [
            'https://www.gstatic.com/charts/loader.js',
            'https://www.google.com/jsapi',
            asset('js/justgage/raphael-2.1.4.min.js'),
            asset('js/justgage/justgage.js'),
            asset('js/bar-graph/bar-graph.js'),
            asset('/includes/fullcalendar/lib/moment.min.js'),
            asset('/includes/fullcalendar/fullcalendar.min.js'),
            asset('js/dashboard/'.$role->getTemplateName().'.js')
        ];
    }



    public function dashboard_new(){
        if(empty($this->userObject)){
            $user = new User($this->currentUserId);
            $this->userObject = $user;
        }
        $this->fetchDashboardData();

        $role = null;

        switch ($this->userObject->position){
            case User::FI:
                $this->_prepareForFinanceAndInsurance();
                break;
            case User::FINANCE_CONTROLLER:
                $this->_prepareForFinanceController();
                break;
            case User::PARTS_MANAGER:
                $this->_prepareForPartsManager();
                break;
            case User::RETAIL_SALES_CONSULTANTS:
                $role = new RetailSalesConsultant($this->userObject);
                $this->_prepareDashboardData($role);
                break;
            case User::FLEET_SALES_CONSULTANTS:
                $this->_prepareForRetailSalesConsultant();
                break;
            case User::FLEET_SALES_MANAGER:
                $this->_prepareForFleetSalesManager();
                break;
            case User::SALES_MANAGER:
                $this->_prepareForSalesManager();
                break;
            case User::STOCK_CONTROLLER:
                $this->_prepareForStockController();
                break;
            case User::PARTS_SALES_REP:
                $this->_prepareForPartsSalesRep();
                break;
            case User::SERVICE_MANAGER:
                $this->_prepareForServiceManager();
                break;
            case User::SERVICE_ADVISERS:
                $this->_prepareForServiceAdviser();
                break;
            default:
                break;
        }

        $this->render('dashboard/my_dashboard');
        return;
    }

    /**
     * Load user's metrics data from data base
     */
    protected function fetchUserMetricsData(){
        $overrideRole = $this->request->param('override_role');

        if(!$overrideRole){
            $data = DataSource::Query($this->userObject);
            $this->metricsData = $data['result']['Results'];
            $this->excellence = $data['result']['Excellence'];
        }else{
            // Todo: For multiple role support
        }
    }

    protected function fetchDashboardData(){
        $this->dataForView['Results']       = [];
        $this->dataForView['Registered']    = Ranking::NOT_REGISTERED;
        $this->dataForView['Excellence']    = 0;
        $this->dataForView['MyRanking']     = null;
        $this->dataForView['Rankings']      = null;
        $this->dataForView['History']       = null;
        $this->dataForView['Credits']       = null;

        $result = DataSource::Query($this->userObject);
        $this->dataForView['Results'] = $result['result']['Results'];
        $this->dataForView['Excellence'] = $result['result']['Excellence'];

        /**
         * 获取所有的排名, 自己的排名
         */
        // Get the latest ranking date
        $thisPeriod = $this->_getThisPeriod($this->userObject);
        // 获取了所有的 Rankings: Get all rankings
        $rankings = Ranking::Query($this->userObject, $thisPeriod);
        $this->dataForView['Rankings'] = $rankings;

        $myRanking = null;
        $currentUserRankingRecord = Ranking::Query($this->userObject, $thisPeriod, true);
        if($currentUserRankingRecord){
            $myRanking = $currentUserRankingRecord['ranking'];
            $this->dataForView['Registered'] = $currentUserRankingRecord['registered'];
        }

        /**
         * 计算历史数据
         */
        $this->dataForView['History'] = History::All($this->userObject);

        /**
         * 计算Credits
         */
        $this->dataForView['Credits'] = Credit::QueryByUserAndYearPeriod($this->userObject,env('YEAR',2017));

        /**
         * 以上是基础数据, 以下为页面中的特定数据
         */

        // 获取 Regional 的 Rankings: 实际就是结合上一步计算自己的排名
        $regionalRanking = Ranking::countRegionalRankingLessThan($this->userObject, $thisPeriod, $myRanking);
        if($regionalRanking){
            $this->dataForView['MyRanking'] = $regionalRanking + 1;
        }

        // 处理 Leader Board 的表格: Leader board 只有5个位置
        $iAmInTopList = false;
        $leaderBoardTableData = [];
        foreach ($rankings as $index=>$item) {
            if($index<Ranking::LEADER_BOARD_TABLE_MAX_ROW){
                if($item['member_id'] == $this->userObject->getEmployeeCode()){
                    $iAmInTopList = true;
                }
                $leaderBoardTableData[] = $item;
            }else{
                // 已经超出了前五名
                if(!$iAmInTopList){
                    if($item['member_id'] == $this->userObject->getEmployeeCode()){
                        $leaderBoardTableData[Ranking::LEADER_BOARD_TABLE_MAX_ROW - 1] = $item;
                        break;
                    }
                }
            }
        }
        $this->dataForView['leaderBoardTableData'] = $leaderBoardTableData;
        // 处理 Leader Board 的表格 结束

        // GAGA indicator
        $this->_handleGagaIndicatorData();
        // GAGA indicator end
    }

    /**
     * This function is for "My Dashboard" menu item
     */
    public function dashboard(){
        if(empty($this->userObject)){
            $user = new User($this->currentUserId);
            $this->userObject = $user;
        }
        $user = $this->userObject;

        $selected_role = $this->getUserRole();

        if($this->userHasMultipleRoles){
            // todo: Load data for multiple roles
        }

//        $ytd=0;
//        $lifetime=0;
//        $monthly='';
//        $metrics='';
//        $min=0;
//        $max=100;
//        $color="#CCCCC";
//        $txt="";
//        $dollar="";
//        $excellence=0;
//        $aryCredits=$Application['User']['Credits'];
//        $training='';

        $override_results = null;

        if (!empty($selected_role)) {
//            $override_results = $Application['User']['multiple_role_metrics'][$selected_role]['Results'];
        }


        if ($user){

            /**
             * 尝试还原 db.php 中的 fetch_current_user 方法
             * Use $this->>dataForView to replace the $row
             */
            $this->dataForView['Results']       = [];
            $this->dataForView['Registered']    = Ranking::NOT_REGISTERED;
            $this->dataForView['Excellence']    = 0;
            $this->dataForView['MyRanking']     = null;
            $this->dataForView['Rankings']      = null;
            $this->dataForView['History']       = null;
            $this->dataForView['Credits']       = null;

            $result = DataSource::Query($user);
            $this->dataForView['Results'] = $result['result']['Results'];
            $this->dataForView['Excellence'] = $result['result']['Excellence'];

            /**
             * 获取所有的排名, 自己的排名
             */
            // Get the latest ranking date
            $thisPeriod = $this->_getThisPeriod($user);
            // 获取了所有的 Rankings: Get all rankings
            $rankings = Ranking::Query($user, $thisPeriod);
            $this->dataForView['Rankings'] = $rankings;

            $myRanking = null;
            $currentUserRankingRecord = Ranking::Query($user, $thisPeriod, true);
            if($currentUserRankingRecord){
                $myRanking = $currentUserRankingRecord['ranking'];
                $this->dataForView['Registered'] = $currentUserRankingRecord['registered'];
            }

            /**
             * 计算历史数据
             */
            $this->dataForView['History'] = History::All($user);

            /**
             * 计算Credits
             */
            $this->dataForView['Credits'] = Credit::QueryByUserAndYearPeriod($user,env('YEAR',2017));

            /**
             * 以上是基础数据, 以下为页面中的特定数据
             */

            // 获取 Regional 的 Rankings: 实际就是结合上一步计算自己的排名
            $regionalRanking = Ranking::countRegionalRankingLessThan($user, $thisPeriod, $myRanking);
            if($regionalRanking){
                $this->dataForView['MyRanking'] = $regionalRanking + 1;
            }

            // 处理 Leader Board 的表格: Leader board 只有5个位置
            $iAmInTopList = false;
            $leaderBoardTableData = [];
            foreach ($rankings as $index=>$item) {
                if($index<Ranking::LEADER_BOARD_TABLE_MAX_ROW){
                    if($item['member_id'] == $user->getEmployeeCode()){
                        $iAmInTopList = true;
                    }
                    $leaderBoardTableData[] = $item;
                }else{
                    // 已经超出了前五名
                    if(!$iAmInTopList){
                        if($item['member_id'] == $user->getEmployeeCode()){
                            $leaderBoardTableData[Ranking::LEADER_BOARD_TABLE_MAX_ROW - 1] = $item;
                            break;
                        }
                    }
                }
            }
            $this->dataForView['leaderBoardTableData'] = $leaderBoardTableData;
            // 处理 Leader Board 的表格 结束

            // GAGA indicator
            $this->_handleGagaIndicatorData();
            // GAGA indicator end
        }

        $this->render('dashboard/main');
        return;
    }

    /**
     * 综合各种情况, 获取当前登陆用户的 position
     * @return string | null
     */
    public function setUserCurrentRoleAndTableName(){
        // 先尝试获取是否用户提交了 asRole, 这个值应该是数据表的名字
        $asRole = $this->request->param('asRole');
//        $this->userHasMultipleRoles = !is_null($this->request->param('override_role'));

        if($asRole){
            // For multiple role support, 用户是有多个角色的, 但是此次请求使用当前找到的角色
            $this->userHasMultipleRoles = count($this->userObject->getPositions()) > 1;
            $abbr = DataSource::nissan_get_abbr_from_table_name($asRole);
            if($abbr){
                $this->asRole = $abbr;
            }
        }else{
            $this->asRole = $this->userObject->position;
            $this->targetTableName = DataSource::nissan_get_table_name_from_abbr($this->asRole);
        }
    }

    private function _handleGagaIndicatorData(){
        $data= $this->dataForView['Results'];
        $ytd=0;
        $lifetime=0;
        $monthly='';
        $metrics='';
        $min=0;
        $max=100;
        $color="#CCCCC";
        $txt="";
        $dollar="";
        $excellence=0;
        $aryCredits=$this->dataForView['Credits'];
        $training='';

        for($i=0; $i<12; $i++)
        {
            $period=mktime(0,0,0,4+$i,1,env('YEAR',2018));
            if(isset($aryCredits[date("M-Y", $period)]))
            {
                $ytd=$aryCredits[date("M-Y", $period)]['ytd'];

                $monthly.=(empty($monthly) ? '' : ',') . "['" . date("M", $period) . "'," . $aryCredits[date("M-Y", $period)]['mtd'] . "]";
            }
            else
            {
                $monthly.=(empty($monthly) ? '' : ',') . "['" . date("M", $period) . "',0]";

            }
            if (isset($data[date("M-Y", $period)]))
            {
                $lifetime=(isset($data[date("M-Y", $period)]['lifetime']) ? $data[date("M-Y", $period)]['lifetime'] : $data[date("M-Y", $period)]['credit_mtd']);
                $excellence=$data[date("M-Y", $period)]['excellence'];
            }

        }

        $this->dataForView['yearToDateTotal'] = $ytd;
        $this->dataForView['minLevel'] = 0;
        $this->dataForView['maxLevel'] = 3000;
    }

    private function _handleRanking($rows, User $user){
        $result = [];
        foreach ($rows as $row) {
            $result[] = $row;
            if($row['member_id'] == $user->getEmployeeCode()){
                $this->dataForView['Registered'] = $row['registered'];
            }
        }
        return $result;
    }

    /**
     * Generate the "this period" data
     * @param User $user
     * @return Carbon|null|string
     */
    private function _getThisPeriod(User $user){
        $thisPeriod = date('Y-m').'-01';
        $thisPeriod = Carbon::createFromFormat('Y-m-d',$thisPeriod);

        if($period = Ranking::QueryThisPeriod($user)){
            $thisPeriod = $period;
        }
        return $thisPeriod;
    }
}