<?php
/**
 * Created by PhpStorm.
 * User: justinwang
 * Date: 23/7/18
 * Time: 5:02 PM
 */

namespace App\controller;

use App\core\BaseController;
use App\models\nissan\Credit;
use App\models\nissan\DataSource as NissanDataSource;
use App\models\nissan\History;
use App\models\nissan\Ranking;
use App\models\User;
use Carbon\Carbon;
use function Couchbase\defaultDecoder;
use Klein\Request;
use Klein\Response;

class DashboardController extends BaseController
{
    protected $currentUserId = null;

    /**
     * @var User
     */
    protected $userObject = null;

    public function __construct(Request $request, Response $response)
    {
        parent::__construct($request, $response);
        $userData = session_get('user_data_array',true);
        if($userData && isset($userData['id'])){
            $this->currentUserId = $userData['id'];
            $this->userObject = new User($this->currentUserId);
        }else{
            // Session expired, go to login
            $response->redirect('/')->send();
            exit;
        }
    }

    /**
     * Before render hook
     * @param null $param
     */
    public function beforeRender($param = null)
    {
        parent::beforeRender($param); // TODO: Change the autogenerated stub
        if($this->userObject){
            $this->dataForView['user'] = $this->userObject;
            // 从原来的代码看, 似乎这两个也是必须的
            $this->dataForView['positions'] =
                NissanDataSource::GetPositionList($this->userObject);

            $this->dataForView['multiple_role_metrics'] =
                NissanDataSource::GetDataAllPositions($this->userObject);

            $this->dataForView['table_role_array'] =
                NissanDataSource::GetTableRoleMetrics($this->userObject);
        }
    }

    /**
     * This function is for "My Dashboard" menu item
     */
    public function dashboard(){
        if(empty($this->userObject)){
            $user = new User($this->currentUserId);
            $this->userObject = $user;
        }
        $user = $this->userObject;

        if ($user){
            /**
             * 尝试还原 db.php 中的 fetch_current_user 方法
             * Use $this->>dataForView to replace the $row
             */
            $this->dataForView['Results']       = [];
            $this->dataForView['Registered']    = Ranking::NOT_REGISTERED;
            $this->dataForView['Excellence']    = 0;
            $this->dataForView['MyRanking']     = null;
            $this->dataForView['Rankings']      = null;
            $this->dataForView['History']       = null;
            $this->dataForView['Credits']       = null;

            $result = NissanDataSource::Query($user);
            $this->dataForView['Results'] = $result['result']['Results'];
            $this->dataForView['Excellence'] = $result['result']['Excellence'];

            /**
             * 获取所有的排名, 自己的排名
             */
            // Get the latest ranking date
            $thisPeriod = $this->_getThisPeriod($user);
            // 获取了所有的 Rankings: Get all rankings
            $rankings = Ranking::Query($user, $thisPeriod);
            $this->dataForView['Rankings'] = $rankings;

            $myRanking = null;
            $currentUserRankingRecord = Ranking::Query($user, $thisPeriod, true);
            if($currentUserRankingRecord){
                $myRanking = $currentUserRankingRecord['ranking'];
                $this->dataForView['Registered'] = $currentUserRankingRecord['registered'];
            }

            /**
             * 计算历史数据
             */
            $this->dataForView['History'] = History::All($user);

            /**
             * 计算Credits
             */
            $this->dataForView['Credits'] = Credit::QueryByUserAndYearPeriod($user,env('YEAR',2017));

            /**
             * 以上是基础数据, 以下为页面中的特定数据
             */

            // 获取 Regional 的 Rankings: 实际就是结合上一步计算自己的排名
            $regionalRanking = Ranking::countRegionalRankingLessThan($user, $thisPeriod, $myRanking);
            if($regionalRanking){
                $this->dataForView['MyRanking'] = $regionalRanking + 1;
            }

            // 处理 Leader Board 的表格: Leader board 只有5个位置
            $iAmInTopList = false;
            $leaderBoardTableData = [];
            foreach ($rankings as $index=>$item) {
                if($index<Ranking::LEADER_BOARD_TABLE_MAX_ROW){
                    if($item['member_id'] == $user->getEmployeeCode()){
                        $iAmInTopList = true;
                    }
                    $leaderBoardTableData[] = $item;
                }else{
                    // 已经超出了前五名
                    if(!$iAmInTopList){
                        if($item['member_id'] == $user->getEmployeeCode()){
                            $leaderBoardTableData[Ranking::LEADER_BOARD_TABLE_MAX_ROW - 1] = $item;
                            break;
                        }
                    }
                }
            }
            $this->dataForView['leaderBoardTableData'] = $leaderBoardTableData;
            // 处理 Leader Board 的表格 结束

            // GAGA indicator
            $this->_handleGagaIndicatorData();
            // GAGA indicator end
        }

        $this->render('dashboard/main');
        return;
    }

    private function _handleGagaIndicatorData(){
        $data= $this->dataForView['Results'];
        $ytd=0;
        $lifetime=0;
        $monthly='';
        $metrics='';
        $min=0;
        $max=100;
        $color="#CCCCC";
        $txt="";
        $dollar="";
        $excellence=0;
        $aryCredits=$this->dataForView['Credits'];
        $training='';

        for($i=0; $i<12; $i++)
        {
            $period=mktime(0,0,0,4+$i,1,env('YEAR',2018));
            if(isset($aryCredits[date("M-Y", $period)]))
            {
                $ytd=$aryCredits[date("M-Y", $period)]['ytd'];

                $monthly.=(empty($monthly) ? '' : ',') . "['" . date("M", $period) . "'," . $aryCredits[date("M-Y", $period)]['mtd'] . "]";
            }
            else
            {
                $monthly.=(empty($monthly) ? '' : ',') . "['" . date("M", $period) . "',0]";

            }
            if (isset($data[date("M-Y", $period)]))
            {
                $lifetime=(isset($data[date("M-Y", $period)]['lifetime']) ? $data[date("M-Y", $period)]['lifetime'] : $data[date("M-Y", $period)]['credit_mtd']);
                $excellence=$data[date("M-Y", $period)]['excellence'];
            }

        }

        $this->dataForView['yearToDateTotal'] = $ytd;
        $this->dataForView['minLevel'] = 0;
        $this->dataForView['maxLevel'] = 3000;
    }

    private function _handleRanking($rows, User $user){
        $result = [];
        foreach ($rows as $row) {
            $result[] = $row;
            if($row['member_id'] == $user->getEmployeeCode()){
                $this->dataForView['Registered'] = $row['registered'];
            }
        }
        return $result;
    }

    /**
     * Generate the "this period" data
     * @param User $user
     * @return Carbon|null|string
     */
    private function _getThisPeriod(User $user){
        $thisPeriod = date('Y-m').'-01';
        $thisPeriod = Carbon::createFromFormat('Y-m-d',$thisPeriod);

        if($period = Ranking::QueryThisPeriod($user)){
            $thisPeriod = $period;
        }
        return $thisPeriod;
    }
}