<?php
/**
 * Created by PhpStorm.
 * User: justinwang
 * Date: 23/7/18
 * Time: 5:02 PM
 */

namespace App\controller;

use App\core\BaseController;
use App\models\Company;
use App\models\nissan\Credit;
use App\models\nissan\DataSource;
use App\models\nissan\Events;
use App\models\nissan\History;
use App\models\nissan\Ranking;
use App\models\role\FI;
use App\models\role\FinanceController;
use App\models\role\FleetSalesConsultant;
use App\models\role\FleetSalesManager;
use App\models\role\IRole;
use App\models\role\PartsManager;
use App\models\role\PartsSalesRep;
use App\models\role\RetailSalesConsultant;
use App\models\role\SalesManager;
use App\models\role\ServiceAdviser;
use App\models\role\ServiceManager;
use App\models\role\StockController;
use App\models\User;
use App\models\utils\LifetimeUtil;
use App\models\utils\RoleFactory;
use Carbon\Carbon;
use Klein\Request;
use Klein\Response;

class DashboardController extends BaseController
{
    protected $currentUserId = null;

    /**
     * @var User
     */
    protected $userObject = null;
    /**
     * If the current user has multiple roles at same time
     * @var bool
     */
    protected $userHasMultipleRoles = false;
    protected $userPositions = [];  // All current user's positions go here

    /**
     * 这个是一个要操作的数据表名称, 和用户当前提交上来的 asRole 相关
     * @var null |string
     */
    protected $targetTableName  = null;
    /**
     * 这个是本次请求作为的角色
     * @var null |string
     */
    protected $asRole           = null;

    /**
     * Data for metrics
     * @var null
     */
    protected $metricsData = null;
    protected $excellence = null;

    protected $_clearUserDataSessionWhenDone = false;

    public function __construct(Request $request, Response $response)
    {
        parent::__construct($request, $response);

        $userData = session_get('user_data_array',true);
        if($userData){
            $managerData = session_get('manager_data_array',true);
            if($managerData){
                // Means manager is login and mock him
                $this->_clearUserDataSessionWhenDone = true;
            }

            $regionStaffData = session_get('region_staff_data_array',true);
            if($regionStaffData){
                // Means manager is login and mock him
                $this->_clearUserDataSessionWhenDone = true;
            }
        }

        if(!$userData){
            $userData = session_get('manager_data_array',true);
        }

        if(!$userData){
            $userData = session_get('region_staff_data_array',true);
        }

        if($userData && isset($userData['id'])){
            $this->currentUserId = $userData['id'];
            $this->userObject = new User($this->currentUserId);
            /**
             * 设置用户的角色: Set user roles
             */
            $this->setUserCurrentRoleAndTableName();
            /**
             * 设置用户的角色 End
             */
        }else{
            // Session expired, go to login
            $response->redirect('/')->send();
            exit;
        }
    }

    /**
     * Before render hook
     * @param null $param
     */
    public function beforeRender($param = null)
    {
        parent::beforeRender($param); // TODO: Change the autogenerated stub
        if($this->userObject){
            $this->dataForView['user'] = $this->userObject;
        }

        // 表示发现现在是 manager 在 mock 他的组员
        if($this->_clearUserDataSessionWhenDone && !$this->userObject->isSuperUser() && !$this->userObject->isRegionsManager()){
            $this->dataForView['dashboardMenuOnly'] = true;
        }
    }

    /**
     * @param null $param
     */
    public function afterRender($param = null)
    {
        parent::afterRender($param);
        // 表示发现现在是 manager 在 mock 他的组员, 在数据渲染完毕之后把储存普通用户的 session 清空
        if($this->_clearUserDataSessionWhenDone){
            session_set('user_data_array', []);
        }
    }

    /**
     * Retrieve data and pass to the view by Given role and year
     * @param IRole $role
     * @param null $ytd
     */
    private function _prepareDashboardData(IRole $role, $ytd = null){
        $ytd = is_null($ytd) ? env('YEAR',2017) : $ytd;
        $this->dataForView['dashboard'] = $role->getDashboardViewData($this->dataForView,$ytd);
        $this->dataForView['calendar_events'] = Events::LoadForCalendarEvents();
        $this->dataForView['metrics_template_file_name'] = $role->getTemplateName();
        $this->dataForView['team_members'] = $this->userObject->getTeamMembers();

        $this->dataForView['extra_css'] = [
            asset('/includes/fullcalendar/fullcalendar.min.css')
        ];
        $this->dataForView['extra_js'] = [
            'https://www.gstatic.com/charts/loader.js',
            'https://www.google.com/jsapi',
            asset('js/justgage/raphael-2.1.4.min.js'),
            asset('js/justgage/justgage.js'),
            asset('js/bar-graph/bar-graph.js'),
            asset('/includes/fullcalendar/lib/moment.min.js'),
            asset('/includes/fullcalendar/fullcalendar.min.js'),
            asset('js/dashboard/utils.js')
        ];
    }

    /**
     * For DSM dashboard
     */
    private function _prepareDashboardDataForDSM(){
        $this->dataForView['extra_css'] = [
        ];
        $this->dataForView['extra_js'] = [
            asset('js/dsm_utils.js')
        ];
    }

    /**
     * For DSM dashboard
     */
    private function _prepareDashboardDataForNissanSuper(){
        $this->dataForView['extra_css'] = [
        ];
        $this->dataForView['extra_js'] = [
            asset('js/dsm_utils.js?version=1')
        ];
    }

    /**
     * Dashboard request handler
     */
    public function dashboard(){
        if(empty($this->userObject)){
            $user = new User($this->currentUserId);
            $this->userObject = $user;
        }

        $this->dataForView['currentUri'] = 'dashboard';

        $viewToRender = 'dashboard/my_dashboard';


        // Todo: Check if user is a regular employee or not
        if($this->userObject->position === User::NISSAN_SUPER){
            // Nissan admin user login
            $viewToRender = 'dashboard/nissan_super_dashboard';
            $regions = $this->userObject->getManagedRegions();
            $this->dataForView['regions'] = $regions;
            $this->_prepareDashboardDataForNissanSuper();
        }elseif($this->userObject->isDealersOwner()){
            // Load dealers' owner view
            $viewToRender = 'dashboard/dealer_owner_dashboard';
        }elseif ($this->userObject->isRegionsManager()){
            // Load regions' sales manager view
            $viewToRender = 'dashboard/region_sales_manger_dashboard';
            $regions = $this->userObject->getManagedRegions();
            $this->dataForView['regions'] = $regions;
            //
            $this->_prepareDashboardDataForDSM();
        }else{
            // Load regular employee's view
            /**
             * @var IRole $role
             */
            $role = null;

            $role = RoleFactory::GetRole($this->userObject->position, $this->userObject);

            if(is_null($role)){
                echo 'No matched role and view found';
                return;
            }
            /**
             * Inject All necessary data to the view
             */
            $this->fetchDashboardData();
            $this->_prepareDashboardData($role);
        }
        // Render the view

        $this->render($viewToRender);
        return;
    }

    /**
     * Someone's lifetime revenue page
     */
    public function lifetime(){
        if(empty($this->userObject)){
            $user = new User($this->currentUserId);
            $this->userObject = $user;
        }
        $this->dataForView['currentUri'] = 'dashboard';

        /**
         * Get Data
         */
        $data = DataSource::Query($this->userObject);
        $results = $data['result']['Results'];

        $lifetime   = 0;
        $monthly    = [];
        $carbon = Carbon::create(env('YEAR'),3,1);
        foreach (range(0,11) as $i) {
            $index = $carbon->addMonth()->format('M-Y');
            if(isset($results[$index])){
                $lifetime = (isset($results[$index]['lifetime']) ? $results[$index]['lifetime'] : $results[$index]['credit_mtd']);
                $monthly[] = [$index, $results[$index]['credit_mtd']];
            }else{
                $monthly[] = [$index, 0];
            }
        }
        $lifetimeUtil = LifetimeUtil::GetInstance($lifetime);

        $historyRows = History::GetLifetime($this->userObject);
        $history = [];

        $now = Carbon::now();
        if( $now->month <= 3 || env('YEAR')== date('Y')-1 ){
            $currentYearData = array_shift($historyRows);
            $historyRows[0] = $currentYearData;
            $historyRows[0][0] = ($now->year -1).'' ;
        }

        /**
         * Need to handle the Fast Finish credits
         */
        foreach ($historyRows as $historyRow) {
            $subTotal = floatval($historyRow[1]);
            if($historyRow[3] > 0){
                // Has FF
                $subTotal += $historyRow[3];
            }
            if($subTotal > 0){
                $history[] = [
                    $historyRow[0],
                    $subTotal
                ] ;
            }


        }

        $this->dataForView['dashboard'] = [
            'lifeTime'=>$lifetime,
            'lifetimeUtil'=>[
                'level_color'=>$lifetimeUtil->color,
                'next_level'=>$lifetimeUtil->next_level,
                'lifetime_to_reach_credits'=>$lifetimeUtil->lifetime_to_reach_credits,
            ],
            'gaga_data' =>$lifetimeUtil->getGagaData(),
            'max'       =>LifetimeUtil::Platinum,
            'monthly'   =>$monthly,
            'history'   =>$history
        ];

        $this->dataForView['extra_js'] = [
            'https://www.gstatic.com/charts/loader.js',
            'https://www.google.com/jsapi',
            asset('js/justgage/raphael-2.1.4.min.js'),
            asset('js/justgage/justgage.js'),
            asset('js/dashboard/lifetime.js')
        ];

        $this->render('dashboard/lifetime');
        return;
    }

    /**
     * Load user's metrics data from data base
     */
    protected function fetchUserMetricsData(){
        $data = DataSource::Query($this->userObject);
        $this->metricsData = $data['result']['Results'];
    }

    /**
     * Fetch data for dashboard view and inject
     */
    protected function fetchDashboardData(){
        $this->dataForView['Results']       = [];
        $this->dataForView['Excellence']    = 0;
        $this->dataForView['History']       = null;
        $this->dataForView['Credits']       = null;

        $result = DataSource::Query($this->userObject);
        $this->dataForView['Results'] = $result['result']['Results'];
//        $this->dataForView['Excellence'] = $result['result']['Excellence'];

        /**
         * 获取所有的排名, 自己的排名
         */
        $this->_makeRankingReady();
        /**
         * 获取所有的排名, 自己的排名 end
         */

        /**
         * 计算历史数据
         */
        $this->dataForView['History'] = History::GetAll($this->userObject);

        /**
         * 计算Credits
         */
        $this->dataForView['Credits'] = Credit::QueryByUserAndYearPeriod($this->userObject,env('YEAR',2017));

        /**
         * 以上是基础数据, 以下为页面中的特定数据
         */

        // 处理 Leader Board 的表格: Leader board 只有5个位置
        $this->dataForView['hasPlatinumRanking'] = false;
        $role = RoleFactory::GetRole($this->userObject->position, $this->userObject);
        $this->dataForView['leaderBoardStatusData'] = Ranking::getLeaderBoardData($this->userObject, $this->dataForView['Rankings']);
        if($role->hasPlatinumRanking){
            $this->dataForView['hasPlatinumRanking'] = true;
            $this->dataForView['leaderBoardPlatinumData'] = Ranking::getLeaderBoardData($this->userObject, $this->dataForView['RankingsPlatinum']);
        }
        // 处理 Leader Board 的表格 结束

    }

    /**
     * 获取所有的排名, 自己的排名
     * @return void
     */
    private function _makeRankingReady(){
        // Get the latest ranking date
        $thisPeriod = $this->_getThisPeriod($this->userObject);

        $role = RoleFactory::GetRole($this->userObject->position, $this->userObject);

        // 获取了所有的 Rankings: Get all rankings
        $rankings = Ranking::Query($this->userObject, $thisPeriod, Ranking::AWARD_STATUS);
        $rankingsPlatinum = Ranking::Query($this->userObject, $thisPeriod, Ranking::AWARD_PLATINUM);

        $this->dataForView['Rankings'] = $rankings;
        $this->dataForView['RankingsPlatinum'] = $rankingsPlatinum;

        $statusRanking = '';
        foreach ($rankings as $ranking) {
            if($ranking['member_id'] == $this->userObject->getEmployeeCode()){
                $statusRanking = $ranking['rank'];
                $platinumRanking = $ranking['rank_platinum'];
                break;
            }
        }
        /**
         * Calculate the region and nationally ranking
         */
        $this->dataForView['statusRanking'] = $statusRanking;

        $this->dataForView['platinumRanking'] = '';
        if($role->hasPlatinumRanking){
            //$rankingRegionally = Ranking::countRegionalRankingLessThan($this->userObject,$thisPeriod,$statusRanking);
            //$this->dataForView['rankingRegionally'] = $rankingRegionally ? $rankingRegionally+1 : 1;
            $this->dataForView['platinumRanking'] = $platinumRanking;
        }

    }

    /**
     * 综合各种情况, 获取当前登陆用户的 position
     * Handle user's position; Handle multiple roles situation
     * @return string | null
     */
    public function setUserCurrentRoleAndTableName(){
        /**
         * 先尝试获取是否用户提交了 asRole, 这个值应该是职务的缩写
         * @var string $asRole : Must be the position's abbr
         */
        $this->asRole = $this->request->param('asRole');
        if(empty($this->asRole)){
            $selectedRole = session_get('selected_role');
            if($selectedRole){
                // 用户以前选定的角色, 应该持续使用
                $this->asRole = $selectedRole;
            }
        }else{
            session_set('selected_role',$this->asRole);
        }

        if($this->asRole){
            $this->userObject->position = $this->asRole;
        }

        /**
         * 从现在起, user的 position 就是和提交的 role 请求一样了
         */

        // Find all user's roles
        $this->userPositions = $this->userObject->getPositions();
        $this->userHasMultipleRoles = count($this->userPositions) > 1;

        // By default, give current user a default position
        $this->targetTableName = DataSource::nissan_get_table_name_from_abbr(
            $this->userObject->position
        );

        // Set to the view
        $this->dataForView['userHasMultipleRoles'] = $this->userHasMultipleRoles;
        $this->dataForView['asRole'] = $this->asRole;
        $this->dataForView['currentRoleText'] = DataSource::getRoleNameByAbbr($this->userObject->position);
        $this->dataForView['targetDatabaseTableName'] = $this->targetTableName;
        $this->dataForView['userPositions'] = $this->userPositions;


        /**
         *  userPositions array is in the below structure
            array(2) {
                ["nissan_salesconsultants"]=>
                    string(16) "Sales Consultant"
                ["nissan_salesmanagers"]=>
                    string(13) "Sales Manager"
            }
         *
         */
    }


    /**
     * Generate the "this period" data
     * @param User $user
     * @param string $role
     * @return Carbon|null|string
     */
    protected function _getThisPeriod(User $user, $role = null){
        $thisPeriod = date('Y-m').'-01';
        $thisPeriod = Carbon::createFromFormat('Y-m-d',$thisPeriod);

        if($period = Ranking::QueryThisPeriod($user, $role)){
            $thisPeriod = $period;
        }
        return $thisPeriod;
    }
}
