PROGRAM_NAME="Nissan ELITE"
PROGRAM_SHORT_NAME="ELITE"
PROGRAM_SHORT_NAME_WITH_YEAR="ELITE19"
PROGRAM_I_ELITE="i_ELITE"
PROGRAM_DEALERSHIP="ELITE Dealership"
YEAR=2019
PROGRAM_AWARD_UNIT="Points"
PRODUCT_CHALLENGE_WINNER=""
PAGE_SIZE=12
SUPPORT_EMAIL_ADDRESS=info@nissanelite.com.au
SUPPORT_EMAIL_NAME="NISSAN ELITE SUPPORT"
ADMIN_USER=admin@admin.com
ADMIN_PASSWORD=Pamjo1
dealExcellenceOverviewUrl=http://staging-dealership.nissanelite.com.au
eventRegisterUrl=http://www.nissan-events.com.au/nissanelite/reg
